id: A973C4604
title: Prayer for the Long Life of Dzogchen Rinpoche
type: translation
pechas:
- IF5C14BC5
- I333248E4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:50:34.784264
  last_modified_at: 2023-01-04 11:50:34.784281
  collections:
  - Dzogchen Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IF5C14BC5/4953: 7E56
  I333248E4/965F: 7E56
